const dishes = [
    { keyword: "gazpacho", name: "Гаспачо", price: 195, category: "soup", count: "350 г", image: "img/gazpacho.jpg", kind: "veg" },
    { keyword: "mushroom_soup", name: "Грибной суп-пюре", price: 185, category: "soup", count: "330 г", image: "img/mushroom_soup.jpg", kind: "veg" },
    { keyword: "norway_soup", name: "Норвежский суп", price: 270, category: "soup", count: "330 г", image: "img/norway_soup.jpg", kind: "fish" },
    { keyword: "tom_yum", name: "Том Ям с креветками", price: 365, category: "soup", count: "330 г", image: "img/tomyum.jpg", kind: "fish" },
    { keyword: "ramen", name: "Рамен с яйцом", price: 310, category: "soup", count: "400 г", image: "img/ramen.jpg", kind: "meat" },
    { keyword: "chicken_soup", name: "Куриный суп", price: 230, category: "soup", count: "330 г", image: "img/chicken.jpg", kind: "meat" },

    { keyword: "potato", name: "Жареная картошка с грибами", price: 150, category: "main", count: "250 г", image: "img/potato.jpg", kind: "veg" },
    { keyword: "lasagna", name: "Лазанья", price: 385, category: "main", count: "310 г", image: "img/lasagna.jpg", kind: "meat" },
    { keyword: "cutlet", name: "Котлеты из курицы с картофельным пюре", price: 225, category: "main", count: "280 г", image: "img/cutlet.jpg", kind: "meat" },
    { keyword: "pizza_margherita", name: "Пицца Маргарита", price: 340, category: "main", count: "300 г", image: "img/pizza.jpg", kind: "veg" },
    { keyword: "fish_rice", name: "Рыба с рисом", price: 390, category: "main", count: "280 г", image: "img/fishrice.jpg", kind: "fish" },
    { keyword: "shrimp_pasta", name: "Паста с креветками", price: 410, category: "main", count: "280 г", image: "img/shrimppasta.jpg", kind: "fish" },

    { keyword: "tuna_salad", name: "Салат с тунцом", price: 280, category: "salad", count: "200 г", image: "img/tunasalad.jpg", kind: "fish" },
    { keyword: "egg_bacon_salad", name: "Салат с беконом и яйцом", price: 240, category: "salad", count: "210 г", image: "img/saladwithegg.jpg", kind: "meat" },
    { keyword: "caesar_salad", name: "Салат Цезарь", price: 230, category: "salad", count: "220 г", image: "img/caesar.jpg", kind: "veg" },
    { keyword: "caprese", name: "Капрезе", price: 220, category: "salad", count: "200 г", image: "img/caprese.jpg", kind: "veg" },
    { keyword: "french_fries", name: "Картофель фри", price: 140, category: "salad", count: "180 г", image: "img/frenchfries1.jpg", kind: "veg" },
    { keyword: "potato_wedges", name: "Картофельные дольки", price: 150, category: "salad", count: "200 г", image: "img/frenchfries2.jpg", kind: "veg" },

    { keyword: "apple_juice", name: "Яблочный сок", price: 90, category: "drink", count: "300 мл", image: "img/apple-juice.jpg", kind: "cold" },
    { keyword: "carrot_juice", name: "Морковный сок", price: 110, category: "drink", count: "300 мл", image: "img/carrot-juice.jpg", kind: "cold" },
    { keyword: "orange_juice", name: "Апельсиновый сок", price: 120, category: "drink", count: "300 мл", image: "img/orange-juice.jpg", kind: "cold" },
    { keyword: "green_tea", name: "Зелёный чай", price: 80, category: "drink", count: "300 мл", image: "img/greentea.jpg", kind: "hot" },
    { keyword: "black_tea", name: "Чёрный чай", price: 80, category: "drink", count: "300 мл", image: "img/tea.jpg", kind: "hot" },
    { keyword: "cappuccino", name: "Капучино", price: 150, category: "drink", count: "250 мл", image: "img/cappuccino.jpg", kind: "hot" },

    { keyword: "donut", name: "Пончик классический", price: 90, category: "dessert", count: "60 г", image: "img/donuts.jpg", kind: "small" },
    { keyword: "donut_assorted", name: "Пончики ассорти", price: 160, category: "dessert", count: "120 г", image: "img/donuts2.jpg", kind: "small" },
    { keyword: "baklava", name: "Пахлава", price: 110, category: "dessert", count: "80 г", image: "img/baklava.jpg", kind: "small" },
    { keyword: "cheesecake", name: "Чизкейк", price: 180, category: "dessert", count: "130 г", image: "img/checheesecake.jpg", kind: "medium" },
    { keyword: "chocolate_cake", name: "Шоколадный торт", price: 190, category: "dessert", count: "140 г", image: "img/chocolatecake.jpg", kind: "medium" },
    { keyword: "chocolate_cheesecake", name: "Шоколадный чизкейк", price: 230, category: "dessert", count: "180 г", image: "img/chocolatecheesecake.jpg", kind: "large" },
];